apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: simple-app

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- nginx-config.yaml
- nginx-html.yaml
- hpa.yaml

commonLabels:
  app: simple-app
  managed-by: argocd-simple-app

commonAnnotations:
  argocd.argoproj.io/sync-wave: "0"
  deployed-by: gitops-pipeline
  git-repo: https://github.com/spaxqwii/platform-engineering-project

images:
- name: nginx
  newName: nginx
  newTag: 1.25-alpine

replicas:
- count: 2
  name: simple-app
