apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: simple-app

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - configmap.yaml
  - hpa.yaml

labels:
  app: simple-app
  environment: production
  managed-by: argocd
  part-of: platform-engineering

commonAnnotations:
  argocd.argoproj.io/sync-wave: "0"
  deployed-by: gitops-pipeline
  git-repo: https://github.com/spaxqwii/platform-engineering-project

images:
  - name: nginx
    newName: nginx
    newTag: 1.25-alpine

replicas:
  - name: simple-app
    count: 2

#configMapGenerator:
 # - name: nginx-html
 #  behavior: create
 #   literals:
 #     - BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
 #     - GIT_COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "local")
